name: RemoteUPPAAL
description: Schedule builds on UPPAAL (verifyta) remotely and relay output.
version: 0.0.1
author: Tim Gjøderum <thgj93@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.1
  redstone: ^0.6.8
  args: ^0.13.7
  io:
  intl:

#dev_dependencies:
#  test: ^0.12.0
